function file_get_contents(filename,nombre,contador) {
//fetch('https://corsproxy.io/?url='+filename).then((resp) => resp.text()).then(function(data) {
fetch("https://deportesmx.vercel.app/api/proxy?url="+filename).then((resp) => resp.text()).then(function(data) {
//fetch('https://cors.jugorder.de/'+filename).then((resp) => resp.text()).then(function(data) {

var str =data;
var m3u8;
var playbackURL2 = str.search("var playbackURL");
var p2pConfi2= str.search("var p2pConfig");


      var idbutton=contador;
      $('#b'+(idbutton+1)).removeAttr('onclick');
      var codigo=data.substr(playbackURL2, p2pConfi2-playbackURL2);
     
const code = codigo;
      var scriptElement = $("<script>").text(code);
      $("body").append(scriptElement);
      alert('Variable: '+'https://cors.jugorder.de/'+playbackURL);
  //console.log(code);
      //console.log("alert(playbackURL);");
    //$( "#codigoScript" ).html("<script>console.log(code);</script>");
      // $( "#codigoScript" ).html("<script>var contador=0;</script>");
      //console.log(contador);
  //  $( "#codigoScript" ).html("<script><br>console.log("+contador+");</script>");
      //$( "#codigoScript" ).html("<script>console.log(contador++);contador++;</script>");
     // m3u8=html("<script>console.log(playbackURL);</script>");
      

setTimeout(code, 1000);
   
  //    console.log("link: "+m3u8);
                  
                  //if(nombre.at(nombre)==(idbutton+1)){
//$('#b'+(idbutton+1)).attr('onClick', "changeChannel(this,'https://deportesmx.vercel.app/online/player.html?get="+m3u8+"','"+nombre+"');");//}
    $('#b'+(idbutton+1)).attr('onClick', "changeChannel(this,'https://deportesmx.vercel.app/online/player.html?get="+playbackURL+"','"+nombre+"');");
    $('#b'+(idbutton+1)).text(nombre);
//console.log('id '+(idbutton+1)+' : '+m3u8);
});
}

var nombre = ['ESPN 1',
'ESPN 2',
'ESPN 3',
'ESPN 4',
'ESPN 5',
'ESPN 6',
'ESPN 7',
'Win Sports +',
'Win Sports + (Op2)',
'Win Sports',
'Win Play +',
'Fox Sports 1 (Argentina)',
'Fox Sports 2 (Argentina)',
'Fox Sports 3 (Argentina)',
'Dsports',
'Dsports 2',
'Dsports +',
'TNT Sports Chile',
'TNT Sports Argentina',
'ESPN Premium Argentina',
'TyC Sports',
'Telefe',
'TV Pública',
'Liga 1 MAX',
'GolTV',
'VTV +',
'GolPeru',
'ESPN Deportes USA',
'TUDN USA',
'Fox Sports 1 USA',
'Fox Sports 2 USA',
'Universo USA',
'Univisíon USA',
'Universo USA',
'Fox Deportes USA',
'Azteca Deportes MX',
'Fox Sports 1 MX',
'Fox Sports 2 MX',
'Fox Sports 3 MX',
'Fox Sports Premium',
'ESPN MX',
'ESPN 2 MX',
'ESPN 3 MX',
'TVC Deportes MX',
'HI! Sports MX',
'DAZN 1 ES',
'DAZN 2 ES',
'DAZN 3 ES (Solo eventos)',
'DAZN 4 ES (Solo eventos)',
'DAZN LaLiga',
'Movistar+ LaLiga',
'Movistar Liga de Campeones',
'Movistar Liga de Campeones 2',
'Movistar Liga de Campeones 3',
'Caracol TV',
'RCN CO',
'TNT 1 GB',
'TNT 2 GB',
'TNT 3 GB',
'TNT 4 GB',
'Sky Sports Bundesliga 1',
'Sky Sports Bundesliga 2',
'Sky Sports Bundesliga 3',
'Sky Sports Bundesliga 4',
'Sky Sports Bundesliga 5',
'DAZN 1 DE',
'DAZN 2 DE',
'Eleven Sports 1 PT',
'Eleven Sports 2 PT',
'Eleven Sports 3 PT',
'Eleven Sports 4 PT',
'Eleven Sports 5 PT',
'Canal 11 PT',
'Sport TV 1 PT',
'Sport TV 2 PT',
'Sport TV 3 PT',
'Sport TV 4 PT',
'Sport TV 5 PT',
'Sport TV 6 PT',
'Sport TV 1 BR',
'Sport TV 2 BR',
'Sport TV 3 BR',
'Premiere 1 BR',
'Premiere 2 BR',
'Premiere 3 BR',
'Premier Sports 1 Irlanda',
'Premier Sports 2 Irlanda',
'ESPN 1 NL',
'ESPN 2 NL',
'ESPN 3 NL',
'Caliente TV',
'TSN 1',
'TSN 2',
'TSN 3',
'TSN 4',
'TSN 5',
'Vamos ES',
'USA Network',
'SporstNet EAST',
'SN360',
'TyC Sports Internacional',
'Canal 5 MX', 
'TUDN MX', 
'Sky Sports Main Event', 
'Sky Sports Premier League', 
'Sky Sports Football', 
'Sky Sports Cricket', 
'Sky Sports Golf', 
'Sky Sports F1', 
'Sky Sports Tennis', 
'CBS Sports Network', 
'FUTV (EV)', 
'ESPN 1 BR', 
'ESPN 2 BR', 
'ESPN 3 BR', 
'ESPN 4 BR', 
'LaLiga Hypermotion',
'Fox Deportes TUBI'];

var arreglo = ['https://streamtpglobal.com/global1.php?stream=espn',
'https://streamtpglobal.com/global1.php?stream=espn2',
'https://streamtpglobal.com/global1.php?stream=espn3',
'https://streamtpglobal.com/global1.php?stream=espn4',
'https://streamtpglobal.com/global1.php?stream=espn5',
'https://streamtpglobal.com/global1.php?stream=espn6',
'https://streamtpglobal.com/global1.php?stream=espn7',
'https://streamtpglobal.com/global1.php?stream=winplus',
'https://streamtpglobal.com/global1.php?stream=winplus2',
'https://streamtpglobal.com/global1.php?stream=winsports',
'https://streamtpglobal.com/global1.php?stream=winplusonline1',
'https://streamtpglobal.com/global1.php?stream=fox1ar',
'https://streamtpglobal.com/global1.php?stream=fox2ar',
'https://streamtpglobal.com/global1.php?stream=fox3ar',
'https://streamtpglobal.com/global1.php?stream=dsports',
'https://streamtpglobal.com/global1.php?stream=dsports2',
'https://streamtpglobal.com/global1.php?stream=dsportsplus',
'https://streamtpglobal.com/global1.php?stream=tntsportschile',
'https://streamtpglobal.com/global1.php?stream=tntsports',
'https://streamtpglobal.com/global1.php?stream=espnpremium',
'https://streamtpglobal.com/global1.php?stream=tycsports',
'https://streamtpglobal.com/global1.php?stream=telefe',
'https://streamtpglobal.com/global1.php?stream=tv_publica',
'https://streamtpglobal.com/global1.php?stream=liga1max',
'https://streamtpglobal.com/global1.php?stream=goltv',
'https://streamtpglobal.com/global1.php?stream=vtvplus',
'https://streamtpglobal.com/global1.php?stream=golperu',
'https://streamtpglobal.com/global1.php?stream=espndeportes',
'https://streamtpglobal.com/global1.php?stream=tudn_usa',
'https://streamtpglobal.com/global1.php?stream=fox_1_usa',
'https://streamtpglobal.com/global1.php?stream=fox_2_usa',
'https://streamtpglobal.com/global1.php?stream=universo_usa',
'https://streamtpglobal.com/global1.php?stream=univision_usa',
'https://streamtpglobal.com/global1.php?stream=universo_usa',
'https://streamtpglobal.com/global1.php?stream=fox_deportes_usa',
'https://streamtpglobal.com/global1.php?stream=azteca_deportes',
'https://streamtpglobal.com/global1.php?stream=foxsportsmx',
'https://streamtpglobal.com/global1.php?stream=foxsports2mx',
'https://streamtpglobal.com/global1.php?stream=foxsports3mx',
'https://streamtpglobal.com/global1.php?stream=foxsportspremium',
'https://streamtpglobal.com/global1.php?stream=espnmx',
'https://streamtpglobal.com/global1.php?stream=espn2mx',
'https://streamtpglobal.com/global1.php?stream=espn3mx',
'https://streamtpglobal.com/global1.php?stream=tvc_deportes',
'https://streamtpglobal.com/global1.php?stream=hisports',
'https://streamtpglobal.com/global1.php?stream=dazn1',
'https://streamtpglobal.com/global1.php?stream=dazn2',
'https://streamtpglobal.com/global1.php?stream=dazn3',
'https://streamtpglobal.com/global1.php?stream=dazn4',
'https://streamtpglobal.com/global1.php?stream=dazn_laliga',
'https://streamtpglobal.com/global1.php?stream=movistarlaliga',
'https://streamtpglobal.com/global1.php?stream=movistarligadecampeones',
'https://streamtpglobal.com/global1.php?stream=movistarligadecampeones2',
'https://streamtpglobal.com/global1.php?stream=movistarligadecampeones3',
'https://streamtpglobal.com/global1.php?stream=caracoltv',
'https://streamtpglobal.com/global1.php?stream=rcnco',
'https://streamtpglobal.com/global1.php?stream=tnt_1_gb',
'https://streamtpglobal.com/global1.php?stream=tnt_2_gb',
'https://streamtpglobal.com/global1.php?stream=tnt_3_gb',
'https://streamtpglobal.com/global1.php?stream=tnt_4_gb',
'https://streamtpglobal.com/global1.php?stream=sky_bundesliga1',
'https://streamtpglobal.com/global1.php?stream=sky_bundesliga2',
'https://streamtpglobal.com/global1.php?stream=sky_bundesliga3',
'https://streamtpglobal.com/global1.php?stream=sky_bundesliga4',
'https://streamtpglobal.com/global1.php?stream=sky_bundesliga5',
'https://streamtpglobal.com/global1.php?stream=dazn1de',
'https://streamtpglobal.com/global1.php?stream=dazn2de',
'https://streamtpglobal.com/global1.php?stream=eleven1_pt',
'https://streamtpglobal.com/global1.php?stream=eleven2_pt',
'https://streamtpglobal.com/global1.php?stream=eleven3_pt',
'https://streamtpglobal.com/global1.php?stream=eleven4_pt',
'https://streamtpglobal.com/global1.php?stream=eleven5_pt',
'https://streamtpglobal.com/global1.php?stream=canal11_pt',
'https://streamtpglobal.com/global1.php?stream=sportv_1pt',
'https://streamtpglobal.com/global1.php?stream=sportv_2pt',
'https://streamtpglobal.com/global1.php?stream=sportv_3pt',
'https://streamtpglobal.com/global1.php?stream=sportv_4pt',
'https://streamtpglobal.com/global1.php?stream=sporttv5',
'https://streamtpglobal.com/global1.php?stream=sporttv6',
'https://streamtpglobal.com/global1.php?stream=sporttvbr1',
'https://streamtpglobal.com/global1.php?stream=sporttvbr2',
'https://streamtpglobal.com/global1.php?stream=sporttvbr3',
'https://streamtpglobal.com/global1.php?stream=premiere1',
'https://streamtpglobal.com/global1.php?stream=premiere2',
'https://streamtpglobal.com/global1.php?stream=premiere3',
'https://streamtpglobal.com/global1.php?stream=premiersports1_irl',
'https://streamtpglobal.com/global1.php?stream=premiersports2_irl',
'https://streamtpglobal.com/global1.php?stream=espn_nl1',
'https://streamtpglobal.com/global1.php?stream=espn_nl2',
'https://streamtpglobal.com/global1.php?stream=espn_nl3',
'https://streamtpglobal.com/global1.php?stream=calientetvmx',
'https://streamtpglobal.com/global1.php?stream=tsn1',
'https://streamtpglobal.com/global1.php?stream=tsn2',
'https://streamtpglobal.com/global1.php?stream=tsn3',
'https://streamtpglobal.com/global1.php?stream=tsn4',
'https://streamtpglobal.com/global1.php?stream=tsn5',
'https://streamtpglobal.com/global1.php?stream=vamoses',
'https://streamtpglobal.com/global1.php?stream=usa_network',
'https://streamtpglobal.com/global1.php?stream=sportnet_east',
'https://streamtpglobal.com/global1.php?stream=sn360',
'https://streamtpglobal.com/global1.php?stream=tycinternacional',
'https://streamtpglobal.com/global1.php?stream=canal5mx',
'https://streamtpglobal.com/global1.php?stream=TUDNMX',
'https://streamtpglobal.com/global1.php?stream=skymain',
'https://streamtpglobal.com/global1.php?stream=skypremierleague',
'https://streamtpglobal.com/global1.php?stream=skyfootball',
'https://streamtpglobal.com/global1.php?stream=skycricket',
'https://streamtpglobal.com/global1.php?stream=skygolf',
'https://streamtpglobal.com/global1.php?stream=skyf1',
'https://streamtpglobal.com/global1.php?stream=skytennis',
'https://streamtpglobal.com/global1.php?stream=cbs_sportsnetwork',
'https://streamtpglobal.com/global1.php?stream=futv',
'https://streamtpglobal.com/global1.php?stream=espn1br',
'https://streamtpglobal.com/global1.php?stream=espn2br',
'https://streamtpglobal.com/global1.php?stream=espn3br',
'https://streamtpglobal.com/global1.php?stream=espn4br',
'https://streamtpglobal.com/global1.php?stream=laligahypermotion',
'https://streamtpglobal.com/global1.php?stream=tubitv1'];

//102
for(var a=0;a<118;a++){
//setTimeout(file_get_contents("https://cors.jugorder.de/"+arreglo[a],nombre[a],a),1000);
setTimeout(file_get_contents("https://deportesmx.vercel.app/api/proxy?url="+arreglo[a],nombre[a],a),1000);
}
